### PR TITLE
Add some missing words, remove extra

### PR DESCRIPTION
**Pull request by brad**
Hi Jason,
I loved your letter, hope you don't mind a tiny bit of editing. I just removed an extra word and added words where they seemed forgotten.

### CODE REVIEW

**Comment by brad** [comment]
Btw, the regular diff is really hard to read, I recommend the "rich diff" tool (the button next to the `<>` button)

**Comment by jasonbobe** [comment]
thank you, i will look at this in a bit! much appreciated!

**Review by jasonbobe — APPROVED** [review]
Thanks for the proofreading @brad 

i appreciate your time!

**Comment by brad** [comment]
No problem Jason, I live on github and can't help making a pull request if I see something off. :smile:

**Pull request merged**
